// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	UserLogin(ctx context.Context, in *UserLoginRegisterRequest, opts ...grpc.CallOption) (*UserLoginRegisterResponse, error)
	UserRegister(ctx context.Context, in *UserLoginRegisterRequest, opts ...grpc.CallOption) (*UserLoginRegisterResponse, error)
	UserTokenRefresh(ctx context.Context, in *UserTokenRefreshRequest, opts ...grpc.CallOption) (*UserTokenRefreshResponse, error)
	UserTokenVerify(ctx context.Context, in *UserTokenVerifyRequest, opts ...grpc.CallOption) (*UserTokenVerifyResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserLogin(ctx context.Context, in *UserLoginRegisterRequest, opts ...grpc.CallOption) (*UserLoginRegisterResponse, error) {
	out := new(UserLoginRegisterResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserRegister(ctx context.Context, in *UserLoginRegisterRequest, opts ...grpc.CallOption) (*UserLoginRegisterResponse, error) {
	out := new(UserLoginRegisterResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UserRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserTokenRefresh(ctx context.Context, in *UserTokenRefreshRequest, opts ...grpc.CallOption) (*UserTokenRefreshResponse, error) {
	out := new(UserTokenRefreshResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UserTokenRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserTokenVerify(ctx context.Context, in *UserTokenVerifyRequest, opts ...grpc.CallOption) (*UserTokenVerifyResponse, error) {
	out := new(UserTokenVerifyResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UserTokenVerify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	UserLogin(context.Context, *UserLoginRegisterRequest) (*UserLoginRegisterResponse, error)
	UserRegister(context.Context, *UserLoginRegisterRequest) (*UserLoginRegisterResponse, error)
	UserTokenRefresh(context.Context, *UserTokenRefreshRequest) (*UserTokenRefreshResponse, error)
	UserTokenVerify(context.Context, *UserTokenVerifyRequest) (*UserTokenVerifyResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) UserLogin(context.Context, *UserLoginRegisterRequest) (*UserLoginRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (UnimplementedUserServiceServer) UserRegister(context.Context, *UserLoginRegisterRequest) (*UserLoginRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (UnimplementedUserServiceServer) UserTokenRefresh(context.Context, *UserTokenRefreshRequest) (*UserTokenRefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserTokenRefresh not implemented")
}
func (UnimplementedUserServiceServer) UserTokenVerify(context.Context, *UserTokenVerifyRequest) (*UserTokenVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserTokenVerify not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserLogin(ctx, req.(*UserLoginRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserRegister(ctx, req.(*UserLoginRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserTokenRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTokenRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserTokenRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserTokenRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserTokenRefresh(ctx, req.(*UserTokenRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserTokenVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTokenVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserTokenVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserTokenVerify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserTokenVerify(ctx, req.(*UserTokenVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserLogin",
			Handler:    _UserService_UserLogin_Handler,
		},
		{
			MethodName: "UserRegister",
			Handler:    _UserService_UserRegister_Handler,
		},
		{
			MethodName: "UserTokenRefresh",
			Handler:    _UserService_UserTokenRefresh_Handler,
		},
		{
			MethodName: "UserTokenVerify",
			Handler:    _UserService_UserTokenVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
